services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        networks:
            - coolify
        environment:
            - SPRING_DATASOURCE_PASSWORD
            - SPRING_DATASOURCE_URL
            - SPRING_DATASOURCE_USERNAME
            - ADMIN_FIRSTNAME
            - ADMIN_LASTNAME
            - ADMIN_USERNAME
            - ADMIN_PASSWORD
            - ADMIN_EMAIL
            - ADMIN_PHONE
            - AUTH_SECRET
            - SPRING_MAIL_USERNAME
            - SPRING_MAIL_PASSWORD

        image: firo1919/maaedbackend
        restart: unless-stopped

networks:
    coolify:
        external: true
